[StyleCop] Fix all the warnings in NumberWithUnit Models
southworks/Recognizers-Text pull request #137
Opened 2019-01-11 15:04 UTC by Aliandi

-SA1003:	Operator should not be followed by whitespace. - Remove whitespace
-SA1009:	Closing parenthesis should not be followed by a space - Remove space
-SA1012:	Opening brace should be followed by a space. - Add space
-SA1413:	Use trailing comma in multi-line initializers - Add trailing comma
-SA1500:	Braces for multi-line statements should not share line - Add space
-SA1305: Variable 'bAdd' should not use Hungarian notation - Rename to resultbAdd
-SA1128: Put constructor initializers on their own line - Move constructor initializer to a different line
-SA1028: Code should not contain trailing whitespace - Remove trailing whitespace

2019-01-11 23:05 UTC, JuanAr requested changes
minor feedback

2019-01-11 23:05 UTC, JuanAr commented on .NET/Microsoft.Recognizers.Text.NumberWithUnit/Models/AbstractNumberWithUnitModel.cs
> +                        bool resultbAdd = true;
Choose a better name like `shouldAddResult` or simply `shouldAdd`

2019-01-14 12:23 UTC, Aliandi commented on .NET/Microsoft.Recognizers.Text.NumberWithUnit/Models/AbstractNumberWithUnitModel.cs
> +                        bool resultbAdd = true;
Renamed to shouldAdd. Changes pushed.

2019-01-14 19:03 UTC, ceciliaavila approved these changes
LGTM

2019-01-15 20:20 UTC, JuanAr commented
Something happened with the new lines in the last commit.

2019-01-16 12:12 UTC, Aliandi commented
Feedback applied

2019-01-18 19:17 UTC, JuanAr approved these changes
👍

2019-01-18 19:21 UTC, closed without merging