[StyleCop] Fix all warnings in Japanese/MergedDateTimeExtractor file
southworks/Recognizers-Text pull request #155
Opened 2019-01-11 18:49 UTC by ceciliaavila

- Renamed file to 'JapaneseMergedExtractor' to match the class name.

2019-01-11 22:25 UTC, JuanAr requested changes
If you add the `&w=1` (Or using the PR diff settings drop down) query string to this PR you'll see only a few lines are modified. However, the entire file seems modified in this PR. This is due to the VS warning regarding mixed new lines.
Keep only the minimum changes needed to fix the SA warnings.

2019-01-14 14:58 UTC, ceciliaavila commented
It is a file renamed, that is why it looks like the entire file has been modified.

2019-01-15 12:44 UTC, Bill7zz approved these changes
LGTM

2019-01-15 20:12 UTC, JuanAr approved these changes

2019-01-15 20:19 UTC, closed without merging