[Recognizers-text][dotnet] Remove unused code from several classes
southworks/Recognizers-Text pull request #225
Opened 2019-01-25 17:55 UTC by Bill7zz

- Remove unused if statement from Japanese/MergeDateTimeParser class
- Remove unused try-catch statement from DateTimeModel class

2019-01-25 17:57 UTC, gasper-az approved these changes
LGTM

2019-01-25 19:48 UTC, JuanAr requested changes
Feedback regarding some functionality changes

2019-01-25 19:48 UTC, JuanAr commented on .NET/Microsoft.Recognizers.Text.DateTime/Models/DateTimeModel.cs
> -                // Nothing to do. Exceptions in parse should not break users of recognizers.
I'm a bit concerned about removing a try catch IF the Parser can throw an exception.

2019-01-25 19:48 UTC, JuanAr commented on .NET/Microsoft.Recognizers.Text.DateTime/Models/DateTimeModel.cs
> -                // Nothing to do. Exceptions in parse should not break users of recognizers.
I think, the PR will be approved maintaining the try/catch structure, removing the unused code if any.
Add a new task to review this specific smelling code: _Try/Catch in code without any explicit action_
Also, add a new issue in our repo to review. And then create the issue in MS repo to socialize and receive feedback and or approval to tackle it.

2019-01-28 14:51 UTC, JuanAr approved these changes
👍

2019-02-18 14:51 UTC, JuanAr commented
Closing because the class was refactored and this is no longer needed.

2019-02-18 14:51 UTC, closed without merging