[Recognizers-Text] Add Matcher signatures
southworks/Recognizers-Text pull request #294
Opened 2019-08-02 18:20 UTC by LCarbonellRod

### Description

- Add signatures of the AaNode class
- Add signatures of the AcAutomaton class
- Add signatures of the IMatcher Interface
- Add signatures of the ITokenizer Interface
- Add signatures of the MatchResult class
- Add signatures of the MatchStrategy class
- Add signatures of the Node class
- Add signatures of the NumberWithUnitTokenizer class
- Add signatures of the SimpleTokenizer class
- Add signatures of the StringMatcher class
- Add signatures of the Token class
- Add signatures of the TrieTree class

2019-08-02 20:03 UTC, Aliandi requested changes

2019-08-02 20:03 UTC, Aliandi commented on Python/libraries/recognizers-text/recognizers_text/Matcher/AaNode.py
> +    @depth.setter
The name of this decorator is not ok. It should be `@fail.setter`

2019-08-02 20:03 UTC, Aliandi commented on Python/libraries/recognizers-text/recognizers_text/Matcher/AaNode.py
> +    def __getitem__(self, c: [T]):
This is not necessary

2019-08-02 20:03 UTC, Aliandi commented on Python/libraries/recognizers-text/recognizers_text/Matcher/AaNode.py
> +    T = TypeVar('T')
What are you using the TypeVar for?

2019-08-02 20:03 UTC, Aliandi commented on Python/libraries/recognizers-text/recognizers_text/Matcher/match_strategy.py
> +    # <summary>
The comments are just for C#, it's not necessary to migrate them

2019-08-02 20:03 UTC, Aliandi commented on Python/libraries/recognizers-text/recognizers_text/Matcher/match_strategy.py
> +    # <summary>
The comments are just for C#, it's not necessary to migrate them

2019-08-02 20:03 UTC, Aliandi commented on Python/libraries/recognizers-text/recognizers_text/Matcher/AaNode.py
> +    def __setitem__(self, c: [T], value):
This is not necessary

2019-08-02 20:03 UTC, Aliandi commented on Python/libraries/recognizers-text/recognizers_text/Matcher/IMatcher.py
> +class IMatcher(ABC):
We don't use the I before the name of the class on python. Interfaces do not exist here and that's a naming convention for an interface

2019-08-02 20:03 UTC, Aliandi commented on Python/libraries/recognizers-text/recognizers_text/Matcher/Node.py
> +    def __getitem__(self, c: [T]):
Not necessary

2019-08-02 20:03 UTC, Aliandi commented on Python/libraries/recognizers-text/recognizers_text/Matcher/Node.py
> +    def __setitem__(self, c: [T], value):
Not necessary

2019-08-02 20:03 UTC, Aliandi commented on Python/libraries/recognizers-text/recognizers_text/Matcher/Token.py
> +    def __init__(self, s: int, l: int, t: str):
i would like to see more expressive names here

2019-08-02 20:03 UTC, Aliandi commented on Python/libraries/recognizers-text/recognizers_text/Matcher/TrieTree.py
> +    # This class should be overrided from AbstractMatcher
Am, what does this mean?

2019-08-02 20:03 UTC, Aliandi commented on Python/libraries/recognizers-text/recognizers_text/Matcher/TrieTree.py
> +class TrieTree:
This class should inherit from AbstractMatcher

2019-08-02 20:03 UTC, Aliandi commented on Python/libraries/recognizers-text/recognizers_text/Matcher/ac_automaton.py
> +class AcAutomaton:
This class should inherit from AbstractMatcher

2019-08-02 20:03 UTC, Aliandi commented on Python/libraries/recognizers-text/recognizers_text/Matcher/IMatcher.py
> +    def init(self, values: list()[T], ids: []) -> None:
use `[T]` instead of `list()[T]`

2019-08-02 20:03 UTC, Aliandi commented on Python/libraries/recognizers-text/recognizers_text/Matcher/string_matcher.py
> +    def init(self, values: list()) -> None:
We can't overload methods on python, [check this documentation](https://pythonspot.com/method-overloading/)

2019-08-02 20:03 UTC, Aliandi commented on Python/libraries/recognizers-text/recognizers_text/Matcher/string_matcher.py
> +    def find(self, tokenized_query: list()) -> list():
Can't overload methods on python :(

2019-08-02 20:03 UTC, Aliandi commented on Python/libraries/recognizers-text/recognizers_text/Matcher/string_matcher.py
> +    def find(self, tokenized_query: list()) -> list():
https://stackabuse.com/overloading-functions-and-operators-in-python/ more docs

2019-08-02 20:03 UTC, Aliandi commented on Python/libraries/recognizers-text/recognizers_text/Matcher/ITokenizer.py
> +class ITokenizer(ABC):
This should not have the I as it is a naming convention for interfaces and we don't use them

2019-08-02 20:58 UTC, Aliandi commented on Python/libraries/recognizers-text/recognizers_text/Matcher/AaNode.py
> +    T = TypeVar('T')
@Maihav, as you said in the other PR, i'd rather not use this and just untype the things, python and static typing are not best friends so i'd just put `[]` to represent a generic list

2019-08-05 12:56 UTC, Aliandi commented on Python/libraries/recognizers-text/recognizers_text/Matcher/IMatcher.py
> +    def find(self, query_text: []) -> list():
the type of the return should be `[]`

2019-08-05 12:56 UTC, Aliandi commented on Python/libraries/recognizers-text/recognizers_text/Matcher/ITokenizer.py
> +    def tokenize(self, _input: str) -> list():
the type of the return should be `[]`

2019-08-05 12:56 UTC, Aliandi commented on Python/libraries/recognizers-text/recognizers_text/Matcher/Node.py
> +    def children(self) -> dict():
the type of the return should be `{}`

2019-08-05 12:56 UTC, Aliandi commented on Python/libraries/recognizers-text/recognizers_text/Matcher/Node.py
> +    def children(self, children) -> dict():
the type of the return should be `{}`

2019-08-05 12:56 UTC, Aliandi commented on Python/libraries/recognizers-text/recognizers_text/Matcher/ac_automaton.py
> +    def insert(self, value: list(), _id: str) -> None:
the type of the second parameter should be `[]`

2019-08-05 12:56 UTC, Aliandi commented on Python/libraries/recognizers-text/recognizers_text/Matcher/number_with_unit_tokenizer.py
> +    def tokenize(self, _input: str) -> list():
the type of the return should be `[]`

2019-08-05 12:56 UTC, Aliandi commented on Python/libraries/recognizers-text/recognizers_text/Matcher/simple_tokenizer.py
> +    def tokenize(self, _input: str) -> list():
the type of the return should be `[]`

2019-08-05 12:56 UTC, Aliandi commented on Python/libraries/recognizers-text/recognizers_text/Matcher/string_matcher.py
> +    def init(self, values: list(), ids: [] = [], values_dictionary: dict() = dict(),
Don't use `list()` and `dict()`, use `[]` or `{}`

2019-08-05 13:59 UTC, Aliandi commented on Python/libraries/recognizers-text/recognizers_text/Matcher/match_result.py
> +class MatchResult(object):
Why does this inherit from `object`?

2019-08-05 13:59 UTC, Aliandi commented on Python/libraries/recognizers-text/recognizers_text/Matcher/number_with_unit_tokenizer.py
> +    def special_tokens_characters(self) -> set():
use `[]` instead of `set()`

2019-08-05 14:03 UTC, LCarbonellRod commented on Python/libraries/recognizers-text/recognizers_text/Matcher/match_result.py
> +class MatchResult(object):
Fixing it!

2019-08-05 14:06 UTC, Aliandi commented
Hey @tellarin, we applied the feedback manually. We are now looking into a way to automatically do this. We'll keep you updated.

2019-08-05 15:43 UTC, merged