Add changes from 2457 to Timex unit tests
southworks/Recognizers-Text pull request #369
Opened 2021-02-09 19:10 UTC by FedericoBernal

2021-02-09 19:41 UTC, Batta32 requested changes
All the methods in Java should be lowerCamelCase.

Example: `DataTypes_Resolver_Date_6th` -> `dataTypesResolverDate6th`

2021-02-09 19:41 UTC, Batta32 commented on Java/libraries/recognizers-text-datatypes-timex-expression/src/test/java/com/microsoft/recognizers/text/datatypes/timex/expression/TestTimexResolver.java
> +        LocalDateTime today = LocalDateTime.of(2020, 10, 20, 0, 0);
```suggestion
        LocalDateTime today = LocalDateTime.of(2020, 10, 20, 0, 0, 0);
```

2021-02-09 19:41 UTC, Batta32 commented on Java/libraries/recognizers-text-datatypes-timex-expression/src/test/java/com/microsoft/recognizers/text/datatypes/timex/expression/TestTimexResolver.java
> +        LocalDateTime today = LocalDateTime.of(2020, 10, 20,0,0);
```suggestion
        LocalDateTime today = LocalDateTime.of(2020, 10, 20, 0, 0, 0);
```

2021-02-09 19:41 UTC, Batta32 commented on Java/libraries/recognizers-text-datatypes-timex-expression/src/test/java/com/microsoft/recognizers/text/datatypes/timex/expression/TestTimexResolver.java
> +        LocalDateTime today = LocalDateTime.of(2020, 10, 20,0,0);
```suggestion
        LocalDateTime today = LocalDateTime.of(2020, 10, 20, 0, 0, 0);
```

2021-02-09 19:41 UTC, Batta32 commented on Java/libraries/recognizers-text-datatypes-timex-expression/src/test/java/com/microsoft/recognizers/text/datatypes/timex/expression/TestTimexResolver.java
> +        LocalDateTime today = LocalDateTime.of(2020, 10, 20, 0, 0);
```suggestion
        LocalDateTime today = LocalDateTime.of(2020, 10, 20, 0, 0, 0);
```

2021-02-09 19:41 UTC, Batta32 commented on Java/libraries/recognizers-text-datatypes-timex-expression/src/test/java/com/microsoft/recognizers/text/datatypes/timex/expression/TestTimexResolver.java
> +        LocalDateTime today = LocalDateTime.of(2021, 1, 22, 0, 0);
```suggestion
        LocalDateTime today = LocalDateTime.of(2021, 1, 22, 0, 0, 0);
```

2021-02-10 14:21 UTC, fran893 approved these changes

2021-02-11 13:06 UTC, Batta32 approved these changes
LGTM

2021-02-12 15:17 UTC, merged