[Java] Refactor AbstractTest & ModelResult
southworks/Recognizers-Text pull request #376
Opened 2021-04-14 13:04 UTC by VictorGrycuk

2021-04-14 13:45 UTC, FedericoBernal approved these changes

2021-04-14 14:23 UTC, Batta32 requested changes
I'm not quite sure to review the `ExtendedModelResult` as this will be a disparity against C#/JS/Python (see [this query](https://github.com/microsoft/Recognizers-Text/search?q=parentText)).

2021-04-14 14:23 UTC, Batta32 commented on Java/libraries/recognizers-text/src/main/java/com/microsoft/recognizers/text/ModelResult.java
> +        this.resolution = resolution;
```suggestion
        this(text, start, end, typeName, resolution);
```

2021-04-14 14:23 UTC, Batta32 commented on Java/tests/src/test/java/com/microsoft/recognizers/text/tests/AbstractTest.java
> -        mapper.addMixIn(ExtendedModelResult.class, ExtendedModelResultMixIn.class);
What happened with the `ExtendedModelResultMixIn` class? Can you review if we need to remove it or not? The `ExtendedModelResult` was removed

2021-04-14 14:23 UTC, Batta32 commented on Java/libraries/recognizers-text/src/main/java/com/microsoft/recognizers/text/ModelResult.java
> +    public final String parentText;
```suggestion
    public final String parentText = null;
```

2021-04-14 14:23 UTC, Batta32 commented on Java/libraries/recognizers-text/src/main/java/com/microsoft/recognizers/text/ModelResult.java
> +        this.parentText = null;
```suggestion
```

2021-04-14 18:39 UTC, Batta32 requested changes

2021-04-14 18:39 UTC, Batta32 commented on Java/libraries/recognizers-text/src/main/java/com/microsoft/recognizers/text/ModelResult.java
> +
Can we remove this? We are not using this

2021-04-14 18:39 UTC, Batta32 commented on Java/tests/src/test/java/com/microsoft/recognizers/text/tests/AbstractTest.java
> +    }
Move this method to after the `public` ones (public -> protected -> private)

2021-04-14 18:39 UTC, Batta32 commented on Java/tests/src/test/java/com/microsoft/recognizers/text/tests/AbstractTest.java
> -        mapper.addMixIn(ExtendedModelResult.class, ExtendedModelResultMixIn.class);
Please, let me know about this, I want to know if we need to remove the class, or if we need to apply another change for this removal

2021-04-14 18:49 UTC, VictorGrycuk commented on Java/tests/src/test/java/com/microsoft/recognizers/text/tests/AbstractTest.java
> +                    // If both properties are equal to 0, it means they doesn't exists, so it will skip the validation
`they doesn't` -> `they don't`

2021-04-14 18:50 UTC, VictorGrycuk commented on Java/tests/src/test/java/com/microsoft/recognizers/text/tests/AbstractTest.java
> +                    // If both properties are equal to 0, it means they doesn't exists, so it will skip the validation
Also, `exists` -> `exist`

2021-04-14 19:37 UTC, Batta32 requested changes
I agree to remove the ExtendedModelResult and use the ModelResult, and also to remove the ExtendedModelResultMixIn, but we need to change the reference of [this](https://github.com/southworks/Recognizers-Text/pull/376/files#diff-2c7744f4662ec42f5af8566f29f0392686661d22370ad2bf1dc5ac64eb6ed5dfL268), to use the [ModelResultMixIn](https://github.com/microsoft/Recognizers-Text/blob/08b488ae1c83127eb93b26d381b8d668b548a620/Java/tests/src/test/java/com/microsoft/recognizers/text/tests/helpers/ModelResultMixIn.java) adding the `@JsonProperty("parentText") String parentText;`

It's weird to remove that mapper.

2021-04-14 19:52 UTC, Batta32 requested changes

2021-04-14 19:52 UTC, Batta32 commented on Java/tests/src/test/java/com/microsoft/recognizers/text/tests/AbstractTest.java
> -        mapper.addMixIn(ExtendedModelResult.class, ExtendedModelResultMixIn.class);
Applying this [change](https://github.com/southworks/Recognizers-Text/pull/376/files#diff-b3c211fd72ec7940e1654281c36961948b46dc6445a0485f7a2da87a08924332R13) requires to update this as follows:
`mapper.addMixIn(ModelResult.class, ModelResultMixIn.class);`

2021-04-14 19:59 UTC, Batta32 approved these changes

2021-04-20 17:07 UTC, Batta32 requested changes

2021-04-20 17:07 UTC, Batta32 commented on Java/tests/src/test/java/com/microsoft/recognizers/text/tests/datetime/DateTimeTest.java
> +        Assert.assertEquals(getMessage(currentCase, "end"), expected.end, actual.end);
This is already validated in `AbstractTest` right? Can we safely remove it?

2021-04-20 17:10 UTC, Batta32 commented on Java/tests/src/test/java/com/microsoft/recognizers/text/tests/datetime/DateTimeTest.java
> +        Assert.assertEquals(getMessage(currentCase, "end"), expected.end, actual.end);
Removed, they are validated in `AbstractTest` class

2021-04-20 18:32 UTC, closed without merging