[#3122] Replace lodash.trimend import by lodash v4.17.21
southworks/Recognizers-Text pull request #387
Opened 2023-07-05 14:42 UTC by JhontSouth

Fixes # 3122
#minor

## Description
This PR allows the use of the _lodash_ modules by the main package and not by individual modules.

## Specific Changes
- Removed every individual module of _lodash_ in the _package.json_ files.
- Modified every import of the individual modules of _lodash_.

## Testing
The following images show the build and the tests running succesfully.
![image](https://github.com/southworks/Recognizers-Text/assets/122501764/6a7e78f7-1e1c-4ed2-954e-8598d570b061)
![image](https://github.com/southworks/Recognizers-Text/assets/122501764/495e0bea-2e0a-4a87-9ad0-c50c423c6291)

2023-07-05 15:14 UTC, ceciliaavila approved these changes

2023-07-06 12:46 UTC, sw-joelmut reviewed
I think the package-lock.json needs to be updated.
Its showing old information, for example the `@microsoft/recognizers-text-date-time` library shows this (image), but in the library it only has the three first ones.
![image](https://github.com/southworks/Recognizers-Text/assets/62260472/e4e56e52-c855-42a7-8b83-631c2951852c)

2023-07-10 19:26 UTC, ceciliaavila requested changes

2023-07-10 19:26 UTC, ceciliaavila commented on JavaScript/packages/recognizers-number-with-unit/package-lock.json
> +          "version": "file:https:/registry.npmjs.org/@microsoft/recognizers-text/-/recognizers-text-1.3.0.tgz",
I think this is not correct. It's still using the packages from the registry.

2023-07-10 19:26 UTC, ceciliaavila commented on JavaScript/packages/recognizers-date-time/package-lock.json
> +          "version": "file:https:/registry.npmjs.org/@microsoft/recognizers-text/-/recognizers-text-1.3.0.tgz",
I think this is not correct. It's still getting the packages from the registry.

2023-07-12 13:01 UTC, sw-joelmut approved these changes

2023-07-13 20:06 UTC, ceciliaavila approved these changes

2023-07-13 20:10 UTC, ceciliaavila commented
/promoted 3124

2023-07-13 20:10 UTC, closed without merging